extends Node

# Boss dialogue bank.
#
# Written offline rather than generated at runtime: that's all the "AI in the
# game" idea actually needs for dialogue, at zero app-size, battery, latency
# and content-safety cost. See MAKE-IT-SELLABLE.md section 9.
#
# Organised by state, then by level theme where the theme matters. Selection is
# anti-repeat (see pick()): a category won't replay a line until it has worked
# through the rest, so a 40-line pool feels like far more than 40.

# --- pre-fight, per level ---------------------------------------------------
const PREFIGHT := {
	1: [
		"So. Your numbers. They're... not great. Let's talk about your 'commitment'.",
		"Grab a seat. Not that one. That one's for people who hit targets.",
		"I'm not angry. I'm just recalibrating my expectations. Downward.",
		"Quick sync! I've booked forty-five minutes to say one disappointing thing.",
		"Before we start — how do you feel about weekends? Philosophically.",
		"I pulled your file. It's mostly blank. That's on you, I think.",
		"You've been 'meeting expectations'. Mine were low. Sit down.",
		"This is a safe space. For me. To criticise you.",
	],
	2: [
		"I've prepared some feedback. It's mostly negative.",
		"Performance review time! I've got a spreadsheet and a grudge.",
		"Rate yourself one to five. Wrong. Try lower.",
		"Your peers had thoughts. Anonymous ones. Devastating ones.",
		"I've scored you 'developing'. You've been here nine years.",
		"Let's align on your growth areas. All of them. Alphabetically.",
		"Your self-assessment said 'exceeds expectations'. That's adorable.",
		"HR says I have to say one positive thing. You're punctual. Moving on.",
	],
	3: [
		"We're restructuring. You're the structure being restructured.",
		"Exciting news! Your job is now four jobs. Same pay. Same you.",
		"The org chart changed. You're the little box with the dotted line.",
		"We're going flat. Everyone reports to me. Especially you.",
		"Synergies were identified. You were one of the things they synergised.",
		"Your department is now a 'pod'. Pods don't get budgets.",
		"Change is hard. Mostly for you. I got equity.",
		"We're 'right-sizing'. Guess which size you are.",
	],
	4: [
		"Weekend's cancelled. So is your lunch. And your dignity.",
		"We ship Friday. Or we all learn what Saturday is for.",
		"I've ordered pizza. It arrives Tuesday. Keep working.",
		"Crunch isn't a culture problem, it's a YOU problem. Faster.",
		"Sleep is a productivity tax. I read that. On a poster. That I made.",
		"The deadline moved up. No, I don't know why. Yes, it's your fault.",
		"I believe in work-life balance. I balance your work against your life.",
		"Two weeks of overtime, and at the end — nothing. Isn't that exciting?",
	],
	5: [
		"Trust fall! You catch me, right? ...Right?",
		"Team building! Studies show it improves morale. Mine, mainly.",
		"We're bonding. Mandatory bonding. Unpaid mandatory bonding.",
		"Let's break down some walls! Metaphorically. Please not literally.",
		"I've been told I'm 'unapproachable'. So: approach. Gently.",
		"This exercise builds trust. And a small amount of nausea.",
		"Everyone said no to this. You didn't answer the email. So.",
	],
	6: [
		"No walls means no place to hide. For YOU, obviously.",
		"Open plan! I can see everyone. Especially your screen.",
		"We removed the walls to encourage collaboration. And surveillance.",
		"There's no privacy here. That's a feature. I decided that.",
		"Great news, your desk is now in the walkway. Very central.",
		"I sit among you now. Like a shark. In a very flat sea.",
	],
	7: [
		"Careful. It's a long way down and I've read the insurance policy.",
		"Team offsite! I picked the venue. It's a bridge. Don't ask.",
		"You wouldn't push your own manager. That'd be insubordinate.",
		"This railing is decorative, apparently. Legal is looking into it.",
	],
	8: [
		"I got the company car. You got the company newsletter.",
		"Don't scratch it. It's leased. Against your bonus, actually.",
		"Nought to sixty in six seconds. Your career: slower.",
		"I'd offer you a lift, but you haven't earned the passenger seat.",
	],
	9: [
		"They said reach for the stars. I meant it as a metaphor. STOP—",
		"There's no oxygen up there. Or performance reviews. Hmm.",
		"You can't fire me into space. There's a policy. There's a POLICY—",
		"Moonshot thinking! That's all I ever asked for! Not like this!",
	],
}

# --- reactions to being hit -------------------------------------------------
const HIT := [
	"Noted!", "That's going in the review!", "Unprofessional!",
	"HR! HR!", "That's a violation of— OW!", "I'll allow it. Once.",
	"Bold choice!", "That's not in your job description!",
	"Let's take this offline— OW!", "Circle back— OOF!",
	"I'm escalating this!", "That's a documented incident!",
	"Ow! That's insubordination!", "You've used your PTO on THIS?",
	"I have an open door policy and you WALKED THROUGH IT!",
	"This is why we can't have nice things! Or you!",
	"Not the face! That's client-facing!",
	"My LinkedIn photo!", "Do you know what I earn?!",
	"That's coming out of your bonus!", "Which was zero! But still!",
	"I'm going to need that in writing!", "This is a hostile work environment!",
	"That was NOT on the agenda!", "You're off the Christmas list!",
	"Ow— let's parking-lot that!", "I have a stand-up in ten minutes!",
	"That's a hard no from me!", "You're spending down your goodwill!",
	"I gave you a MUG once!", "There were DONUTS at that meeting!",
	"That's very much a you problem— OW!", "Let's sync on your future here!",
	"Ow! Ow! Actioned!", "I'm looping in legal!",
	"This is going in the shared drive!", "The one nobody can find!",
	"I'm not mad, I'm— OW, no, I'm mad!",
	"You had SO much potential!", "That's a growth area for you!",
	"I mentored you!", "Badly! But I did!",
	"My door was ALWAYS open!", "Mostly because it was broken!",
	"You'll never make partner!", "We don't have partners! But still!",
]

# --- taunts while guarding ---------------------------------------------------
const TAUNT := [
	"Mmyeah, I'm gonna have to disagree with you there, champ.",
	"Let's put a pin in your 'feelings' and circle back never.",
	"I don't hear a team player. I hear excuses.",
	"Have you tried just... working harder? For free?",
	"That's a 'you' problem. Take it to HR. Oh wait, I'm HR.",
	"Per my last email — which you clearly ignored.",
	"We're a FAMILY here. And you're the disappointing one.",
	"I don't want to micromanage. I want to nano-manage.",
	"Great question. I'm going to answer a different one.",
	"Let's take that offline. Forever. Into a drawer.",
	"I'm going to need you to be more of a self-starter. And a self-finisher.",
	"Work smarter, not harder. Then also harder.",
	"There's no 'I' in team. There is a 'me' though. Interesting.",
	"I read your proposal. Well — I read the subject line.",
	"Let's socialise this idea until it dies of exposure.",
	"You're doing great! That's not a compliment, that's calibration.",
	"I've got an open-door policy. The door leads to another door.",
	"Can you take this on? It's a stretch assignment. It'll stretch you thin.",
	"We value transparency. So: I've already decided.",
	"Let's not reinvent the wheel. Let's reinvent your job description.",
	"I'll be honest with you — no, actually, I won't.",
	"You've got real potential. I said that in 2019 too.",
	"That's above your pay grade. Everything is, really.",
	"Let's get aligned. By which I mean: agree with me.",
	"I'm not saying it's wrong. I'm saying it's yours.",
	"We're all making sacrifices. Mine was emotional availability.",
	"Ownership! That's what I want to see! You owning my mistakes!",
	"Is this a hill you want to die on? It's a small hill. Very unremarkable.",
	"I hear you. I'm choosing not to listen, but I do hear you.",
	"Let's double-click on that. And then never open it again.",
	"You know what I like about you? ...Give me a second.",
	"We should do lunch. Not together. But you should eat, probably.",
	"I'd promote you, but then who'd do the work you do?",
	"Think of this as a learning opportunity. You'll learn a lot about me.",
	"Just spitballing here — what if you did more, but quieter?",
	"I'm going to be your biggest advocate. Silently. In rooms you're not in.",
	"Culture fit is important. And you fit... adjacent to it.",
	"Let's not point fingers. Let's just look at your name on the ticket.",
	"Quick one: could you stay late? It's for morale. Not yours.",
	"I've been where you are. Then I stopped being bad at it.",
	"I'd explain it again, but I'd rather you just felt bad.",
	"Let's take a beat. A long one. Where you reflect.",
	"You're not in trouble. You're in... context.",
	"I'm going to need a doc on that. A living doc. It'll outlive you.",
	"Have you got capacity? Wrong answer. You've got capacity.",
	"I've flagged it. To myself. And I've decided I'm right.",
	"Let's be pragmatic — by which I mean let's do it my way quickly.",
	"That's an interesting perspective from someone at your level.",
	"I'd love your input. Later. Much later. After the decision.",
	"We're a meritocracy. I have merit. You have tasks.",
	"You keep saying 'blocked'. I keep hearing 'unmotivated'.",
	"Perception is reality, and my perception of you is load-bearing.",
	"Let's not over-engineer this. Let's under-resource it instead.",
	"I trust you completely. That's why I check hourly.",
	"Push back all you like. The wall doesn't move, but do try.",
	"You want autonomy? Earn it. In writing. In triplicate.",
	"Every problem is an opportunity. This one's an opportunity for you to fix it.",
	"I don't do politics. I do... strategic relationship management.",
	"Just to be clear, this isn't criticism. It's a downward compliment.",
	"You've been very vocal lately. Consider being less... audible.",
	"I said 'quick win'. You heard 'do it properly'. Classic you.",
	"Nobody's indispensable. Except me. Structurally.",
	"You'll thank me for this. Not soon. But eventually. Probably not.",
	"I'm going to give you some radical candour. Emphasis on the radical.",
	"Let's set some stretch goals. Ambitious ones. Impossible ones.",
	"Is that blocked, or is it just hard? Because hard isn't blocked.",
	"I'd like to see more initiative. Not ideas. Initiative.",
	"We're lean. That's why you're doing three people's jobs.",
	"Your role is evolving. Into something with more evenings.",
	"There's no budget for that. There's budget for my offsite, but not that.",
	"You should be more visible. Come in earlier. Leave later. Be seen.",
	"I've been thinking about your career. Briefly. In a lift.",
	"Great work last quarter! Wrong person? Fine. Great work anyway.",
	"Let's not make this about feelings. Let's make it about your output.",
	"Consider this coaching. Aggressive, unsolicited coaching.",
	"You're a safe pair of hands. Boring. But safe.",
	"I'll champion this upward. Silently. In my head. Forgetfully.",
	"Deadlines are just goals with consequences. Yours has consequences.",
	"You don't need work-life balance, you need work-life prioritisation.",
	"Between us? I have no idea what any of you do. It's great.",
]

# --- when the player whiffs ---------------------------------------------------
const MISS := [
	"Missed. Like your targets.",
	"Swing and a miss! Very on-brand.",
	"Ooh, so close. Like your promotion.",
	"That's the effort I've come to expect.",
	"You telegraph everything. Like your status updates.",
	"Try again. Actually, don't. I'm busy.",
	"Is that in scope for you?",
	"That's going to need another iteration.",
	"Have you considered a different career?",
	"I've seen better follow-through in a stand-up.",
	"Wide. Like your estimates.",
	"Let's call that a learning.",
	"Bless. Genuinely.",
	"You've got the enthusiasm. Not the aim.",
	"Poor execution. I'll note the date.",
	"That one's going in the retro.",
	"Out of scope. Like your ambition.",
	"Was that a punch or a suggestion?",
	"I've had performance reviews land harder.",
	"You'll want to workshop that.",
	"Needs another sprint, that does.",
	"Air. Delicious, well-earned air.",
	"That's a no from me, and from the air.",
	"Have you considered pair-punching? With someone competent?",
	"I'd give that a 'partially meets'.",
	"You've been flagged as a blocker. To yourself.",
	"Swing harder. Or don't. I'm indifferent and busy.",
	"That's the kind of accuracy that gets you a mug.",
	"Nearly! Nearly is the story of your file.",
	"Do you want me to stand still? I could stand still.",
]

# --- low HP: the mask slips ---------------------------------------------------
const LOWHP := [
	"Okay. Okay. Let's — let's take five.",
	"I'm sensing some tension. Is it me?",
	"We can talk about the raise. The raise is on the table!",
	"Fridays! Fridays off! Every Friday! Some Fridays!",
	"I never even READ your reviews! I copy-pasted them!",
	"The pizza party was my idea and I'm SORRY!",
	"You can have the good chair! Take the chair!",
	"I don't actually know what you do! I've never known!",
	"Please. I have a mortgage on a second house.",
	"I'll approve the expenses! ALL of them! Even that one!",
	"Let's find a win-win! Or a win-you! I'd accept a win-you!",
	"I'm a people person! I'm PEOPLE!",
	"Was it the reply-all? It was the reply-all, wasn't it.",
	"My door is open! It's SO open! Look how open!",
	"I could retire. I should retire. Should I retire?",
	"You're my best— you're my only— you're here a lot!",
	"Take the corner office! I'll take the cupboard!",
	"Unlimited PTO! Actually unlimited! Actually take it!",
	"I take it back! All of it! Even the stuff from 2018!",
	"HELP. Somebody. Anybody. Karen from Accounts?",
]

# --- boss goes down -----------------------------------------------------------
const KO := [
	"...okay. Let's not put THAT in the performance review.",
	"I'll... I'll send a calendar invite... to discuss...",
	"Tell my wife... I said... 'per my last email'...",
	"This is... a great learning... for both of us...",
	"I'm going to log off... for the day... possibly the decade...",
	"Well. Someone's getting employee of the month.",
	"Let's regroup Monday. Or never. Never's good.",
	"I see... great things... for you here...",
	"Out of office... indefinitely...",
	"You know what? You've earned that raise. You've EARNED it.",
	"Escalate this... to somebody... who cares...",
	"Circling... back... to the floor...",
	"I'm going to work from home... on the floor...",
	"Put... put me down as a maybe...",
	"Delegating... consciousness...",
	"This is... a really strong quarter... for you...",
	"I'll get the meeting notes... to you... eventually...",
	"Marking myself... away...",
	"Blue sky... I can see the blue sky...",
	"Deprioritising... standing...",
	"You've unblocked yourself... congratulations...",
	"I'm taking that PTO after all...",
]

# --- player goes down ---------------------------------------------------------
const PLAYER_DOWN := [
	"Ha! Back to your desk, champ.",
	"And THAT is why I'm management.",
	"Take the L. Log it. Learn from it. Leave.",
	"I'll put this in your file. Under 'attitude'.",
	"See you at stand-up. Bring a better plan.",
	"That's a performance improvement plan, that is.",
	"Nice try! That's what I'll say. Out loud. Insincerely.",
	"Back to work. The pizza's not going to eat itself.",
	"Let's schedule a follow-up. For never.",
	"I've marked this as 'resolved: won't fix'.",
	"You gave it a go! That's the sort of energy I'll ignore.",
	"Have a think about your future here. It's short.",
	"I'll walk you back to your desk. Slowly. Publicly.",
	"That's what happens when you skip the offsite.",
	"Good effort! Bad outcome! Classic!",
]

# --- gimmick-specific ---------------------------------------------------------
const THROWN := [
	"WHEEE— this is NOT team building!",
	"Put me DOWN! Gently! With respect!",
	"I'm not insured for this!",
	"This is definitely a HR matter!",
	"I'm getting frequent flyer miles!",
	"MY BACK! My beautiful management back!",
	"Is this the trust part?!",
	"I've changed my mind about open plan!",
	"I approve of NONE of this trajectory!",
	"This was NOT on the agenda! Neither was the CEILING!",
	"I'm spinning! Like the narrative usually does!",
	"WHY IS THERE SO MUCH ROOM IN HERE?!",
	"I did NOT sign the waiver!",
	"This is the most upward mobility I've had in years!",
	"Somebody minute this! MINUTE IT!",
]

const PELTED := [
	"That's company property!",
	"Not the stapler! That's MY stapler!",
	"The plant was a GIFT!",
	"You're paying for that keyboard!",
	"That mug says 'World's Okayest Boss'!",
	"Facilities is going to hear about this!",
	"Careful! Some of that's leased!",
	"That printer never worked anyway! Fine! FINE!",
	"You're throwing MY things AT me! There's a symmetry I hate!",
	"Not the monitor! It has my one-to-one notes on it!",
	"This is an asset register issue!",
	"Ow! That was a GIFT from the regional manager!",
	"Stop weaponising the stationery cupboard!",
	"I APPROVED that purchase order!",
]

# --- reactions to a building combo -------------------------------------------
const COMBO_LINES := [
	"Okay, this is a pattern of behaviour!",
	"That's THREE! I'm counting!",
	"You're on a streak! Not a good one! For me!",
	"Somebody get facilities! Or a priest!",
	"This is sustained! This is SUSTAINED!",
	"Is anyone else seeing this?! Anyone?!",
	"You've found a process improvement, haven't you.",
	"I'd like to escalate! To anyone! Upward! Sideways!",
	"That's a velocity I've never seen from you!",
	"NOW you're a self-starter!",
	"Where was THIS energy in Q3?!",
	"You're exceeding expectations! Stop exceeding them!",
	"Great throughput! Terrible context!",
	"This is the initiative I asked for and I hate it!",
	"Consistent delivery! I'm horrified and impressed!",
]

# --- between levels -----------------------------------------------------------
const LEVEL_WIN := [
	"Fine. FINE. But I'm bringing a friend next time.",
	"That's one meeting. There are always more meetings.",
	"You've won the battle. I've won the org chart.",
	"Enjoy it. The next one has a budget.",
	"I'm going to go and think about my choices. Then repeat them.",
	"Rematch. After my lunch. My two-hour lunch.",
	"You'll pay for this. Literally. It's coming out of the team offsite.",
	"Well played. I'm going to go be passive-aggressive elsewhere.",
	"Noted. Filed. Resented.",
	"I'll be back. With a slide deck.",
	"You've made your point. I've made a note.",
	"Let's call that one a draw. It wasn't. But let's.",
]

# --- gimmick-specific: bridge, car, moon --------------------------------------
const BRIDGE := [
	"This is a load-bearing conversation!",
	"I have a strong aversion to gravity!",
	"We could talk about this on the LAND side!",
	"I'm not falling for that. Or off that. Either!",
	"There are guard rails for a REASON!",
	"Health and safety! HEALTH AND SAFETY!",
	"I'll approve the flexible working! FLEXIBLE! WORKING!",
]

const CAR := [
	"That's a lease! You cannot do this to a LEASE!",
	"Mind the paintwork! Mind MY work!",
	"I have three points on my licence and none of them are for THIS!",
	"The insurance does not cover employee grievance!",
	"BEEP BEEP means STOP, apparently!",
	"You are not on the policy!",
]

const MOON := [
	"That is NOT what moonshot thinking means!",
	"There is no WIFI up there! No WIFI!",
	"I'll miss the quarterly! I'LL MISS THE QUARTERLY!",
	"Tell them I was ambitious! Vertically!",
	"This is the furthest anyone has ever escalated anything!",
	"I'm out of office! VERY out of office!",
	"One small step for me, one enormous HR case for you!",
]
